// Device commands ported verbatim from Packaging/installer.
// Generated by scripts/sync-classic-commands.py; control flow lives in engine.rs.
// Packaging/installer/full/install.sh:51
pub const STOP_FULL: &str = r###"
        setprop ctl.stop voyahtune_load 2>/dev/null || exit 1
        stop_wait=0
        while [ "$(getprop init.svc.voyahtune_load)" != "stopped" ]; do
            [ "$stop_wait" -lt 5 ] || exit 1
            sleep 1
            stop_wait=$((stop_wait + 1))
        done
        rm -f /data/local/tmp/voyahtune_load.v2.lock \
            /data/local/tmp/voyah_load.v2.lock
        rm -rf /data/local/tmp/voyah_load.lock
    "###;
// Packaging/installer/full/install.sh:97
pub const NATIVE_READY: &str = r###"
        if pm list packages --user 0 2>/dev/null | grep -qx "package:ru.big.town.anative" \
                && pm path ru.big.town.anative 2>/dev/null | grep -q "^package:" \
                && [ -d /data/user/0/ru.big.town.anative ] \
                && [ -d /data/user_de/0/ru.big.town.anative ]; then
            echo READY
        else
            echo BROKEN
        fi
    "###;
// Packaging/installer/full/install.sh:128
pub const NATIVE_BROADCAST: &str = r###"am broadcast -a com.qinggan.intent.QINGGAN_BOOT_COMPLETE -n ru.big.town.anative/.SetModesReceiverStatic >/dev/null"###;
// Packaging/installer/full/install.sh:184
pub const MOUNT: &str =
    r###"mount -o rw,remount /system 2>/dev/null; mount -o rw,remount / 2>/dev/null"###;
// Packaging/installer/full/install.sh:185
pub const RW_TEST: &str = r###"touch /system/.ovw_rwtest 2>/dev/null && rm -f /system/.ovw_rwtest && echo RW || echo RO"###;
// Packaging/installer/full/install.sh:346
pub const LEGACY_STATE: &str = r###"if [ ! -e '$LEGACY_INIT_DEVICE' ]; then echo MISSING; elif [ ! -f '$LEGACY_INIT_DEVICE' ]; then echo ERROR; else grep -qF '$LEGACY_INIT_MARKER' '$LEGACY_INIT_DEVICE' 2>/dev/null; legacy_grep_status=$?; if [ $legacy_grep_status -eq 0 ]; then echo LEGACY; elif [ $legacy_grep_status -eq 1 ]; then echo CLEAN; else echo ERROR; fi; fi"###;
// Packaging/installer/full/install.sh:391
pub const LEGACY_ROLLBACK: &str = r###"chown 0:0 '$LEGACY_INIT_DEVICE.voyahtune.rollback' && chmod 644 '$LEGACY_INIT_DEVICE.voyahtune.rollback' && /system/bin/sh -n '$LEGACY_INIT_DEVICE.voyahtune.rollback' && restorecon '$LEGACY_INIT_DEVICE.voyahtune.rollback' && mv -f '$LEGACY_INIT_DEVICE.voyahtune.rollback' '$LEGACY_INIT_DEVICE' && restorecon '$LEGACY_INIT_DEVICE' && sync"###;
// Packaging/installer/full/install.sh:450
pub const LEGACY_PUBLISH: &str = r###"chown 0:0 '$LEGACY_INIT_DEVICE.voyahtune.new' && chmod 644 '$LEGACY_INIT_DEVICE.voyahtune.new' && /system/bin/sh -n '$LEGACY_INIT_DEVICE.voyahtune.new' && restorecon '$LEGACY_INIT_DEVICE.voyahtune.new' && mv -f '$LEGACY_INIT_DEVICE.voyahtune.new' '$LEGACY_INIT_DEVICE' && restorecon '$LEGACY_INIT_DEVICE' && sync"###;
// Packaging/installer/full/install.sh:471
pub const BOOT_CLEAN_STAGE: &str = r###"rm -f /system/etc/.voyahtune.setenforce.rc.new /system/etc/.voyahtune.load.rc.new /system/etc/.voyahtune.load.sh.new /system/etc/.voyahtune.setenforce.rc.rollback /system/etc/.voyahtune.load.rc.rollback /system/etc/.voyahtune.load.sh.rollback"###;
// Packaging/installer/full/install.sh:475
pub const BOOT_CLEAN_SNAPSHOT: &str = r###"rm -f /system/etc/.voyahtune.setenforce.rc.previous /system/etc/.voyahtune.setenforce.rc.absent /system/etc/.voyahtune.load.rc.previous /system/etc/.voyahtune.load.rc.absent /system/etc/.voyahtune.load.sh.previous /system/etc/.voyahtune.load.sh.absent"###;
// Packaging/installer/full/install.sh:479
pub const BOOT_STATE: &str = r###"if [ -x /system/etc/init.voyahtune.load.sh ] && grep -qF '/data/local/bin/load.bin' /system/etc/init.voyahtune.load.sh && [ -r /system/etc/init/voyahtune.load.rc ] && grep -qF 'on post-fs-data' /system/etc/init/voyahtune.load.rc && grep -qF '/system/bin/setenforce 0' /system/etc/init/voyahtune.load.rc && grep -qF 'service voyahtune_load' /system/etc/init/voyahtune.load.rc && grep -qF 'MD-priority-before-app-cache-v1' /system/etc/init/voyahtune.load.rc && grep -qF 'enable voyahtune_load' /system/etc/init/voyahtune.load.rc; then echo READY; elif [ ! -e /system/etc/init.voyahtune.load.sh ] && [ ! -e /system/etc/init/voyahtune.setenforce.rc ] && [ ! -e /system/etc/init/voyahtune.load.rc ]; then echo ABSENT; else echo PARTIAL; fi"###;
// Packaging/installer/full/install.sh:489
pub const BOOT_SNAPSHOT: &str = r###"if [ -f /system/etc/init/voyahtune.setenforce.rc ]; then cp -p /system/etc/init/voyahtune.setenforce.rc /system/etc/.voyahtune.setenforce.rc.previous; else : > /system/etc/.voyahtune.setenforce.rc.absent; fi && if [ -f /system/etc/init/voyahtune.load.rc ]; then cp -p /system/etc/init/voyahtune.load.rc /system/etc/.voyahtune.load.rc.previous; else : > /system/etc/.voyahtune.load.rc.absent; fi && if [ -f /system/etc/init.voyahtune.load.sh ]; then cp -p /system/etc/init.voyahtune.load.sh /system/etc/.voyahtune.load.sh.previous; else : > /system/etc/.voyahtune.load.sh.absent; fi && sync"###;
// Packaging/installer/full/install.sh:496
pub const BOOT_ROLLBACK: &str = r###"restore_one() { if [ -f "$1.previous" ]; then cp -p "$1.previous" "$1.rollback" && mv -f "$1.rollback" "$2"; elif [ -f "$1.absent" ]; then rm -f "$2"; else return 1; fi; }; if [ -f /system/etc/.voyahtune.load.rc.absent ]; then rm -f /system/etc/init/voyahtune.load.rc && restore_one /system/etc/.voyahtune.load.sh /system/etc/init.voyahtune.load.sh && restore_one /system/etc/.voyahtune.setenforce.rc /system/etc/init/voyahtune.setenforce.rc; elif [ -f /system/etc/.voyahtune.load.rc.previous ]; then restore_one /system/etc/.voyahtune.load.sh /system/etc/init.voyahtune.load.sh && restore_one /system/etc/.voyahtune.setenforce.rc /system/etc/init/voyahtune.setenforce.rc && restore_one /system/etc/.voyahtune.load.rc /system/etc/init/voyahtune.load.rc; else exit 1; fi && for f in /system/etc/init/voyahtune.setenforce.rc /system/etc/init/voyahtune.load.rc /system/etc/init.voyahtune.load.sh; do [ ! -e "$f" ] || restorecon "$f" || exit 1; done && sync"###;
// Packaging/installer/full/install.sh:528
pub const BOOT_PREPARE: &str = r###"chown 0:0 /system/etc/.voyahtune.load.sh.new /system/etc/.voyahtune.load.rc.new && chmod 755 /system/etc/.voyahtune.load.sh.new && chmod 644 /system/etc/.voyahtune.load.rc.new && grep -qF '/data/local/bin/load.bin' /system/etc/.voyahtune.load.sh.new && grep -qF 'on post-fs-data' /system/etc/.voyahtune.load.rc.new && grep -qF '/system/bin/setenforce 0' /system/etc/.voyahtune.load.rc.new && grep -qF 'service voyahtune_load' /system/etc/.voyahtune.load.rc.new && grep -qF 'MD-priority-before-app-cache-v1' /system/etc/.voyahtune.load.rc.new && grep -qF 'enable voyahtune_load' /system/etc/.voyahtune.load.rc.new && restorecon /system/etc/.voyahtune.load.sh.new /system/etc/.voyahtune.load.rc.new && sync"###;
// Packaging/installer/full/install.sh:541
pub const BOOT_PUBLISH: &str = r###"mv -f /system/etc/.voyahtune.load.sh.new /system/etc/init.voyahtune.load.sh && mv -f /system/etc/.voyahtune.load.rc.new /system/etc/init/voyahtune.load.rc && restorecon /system/etc/init.voyahtune.load.sh /system/etc/init/voyahtune.load.rc && sync"###;
// Packaging/installer/full/install.sh:551
pub const BOOT_READY: &str = r###"if [ -x /system/etc/init.voyahtune.load.sh ] && grep -qF '/data/local/bin/load.bin' /system/etc/init.voyahtune.load.sh && [ -r /system/etc/init/voyahtune.load.rc ] && grep -qF 'on post-fs-data' /system/etc/init/voyahtune.load.rc && grep -qF '/system/bin/setenforce 0' /system/etc/init/voyahtune.load.rc && grep -qF 'service voyahtune_load' /system/etc/init/voyahtune.load.rc && grep -qF 'MD-priority-before-app-cache-v1' /system/etc/init/voyahtune.load.rc && grep -qF 'enable voyahtune_load' /system/etc/init/voyahtune.load.rc; then echo READY; else echo BROKEN; fi"###;
// Packaging/installer/full/install.sh:571
pub const BOOT_REMOVE_OLD: &str = r###"rm -f /system/etc/init/voyahtune.setenforce.rc && test ! -e /system/etc/init/voyahtune.setenforce.rc && sync"###;
// Packaging/installer/full/install.sh:616
pub const APOLLO_FILES: &str = r###"rm -f /data/local/bin/apollo_tech.js /data/local/bin/apollo_tech.js.new /data/local/tmp/voyahtune_apollo.pid /data/local/tmp/voyahtune_apollo.attempt /data/local/tmp/voyahtune_apollo.txt /data/local/tmp/voyahtune_apollo.txt.try /data/local/tmp/voyah_apollo.pid /data/local/tmp/voyah_apollo.down /data/local/tmp/voyah_apollo.disabled /data/local/tmp/voyah_apollo.txt /data/local/tmp/voyah_apollo.txt.1 /data/local/tmp/voyah_apollo.txt.try"###;
// Packaging/installer/full/install.sh:648
pub const APP_CLIENT_MIGRATION: &str = r###"
    fullscreen_csv=$(settings get global voyahtune_fullscreen_apps 2>/dev/null)
    old_ifs=$IFS
    IFS=,
    for app_client_pkg in $fullscreen_csv; do
        IFS=$old_ifs
        case "$app_client_pkg" in
            ""|null|.*|*.|*..*|*[!A-Za-z0-9._]*) IFS=,; continue ;;
        esac
        am force-stop "$app_client_pkg" >/dev/null 2>&1
        IFS=,
    done
    IFS=$old_ifs
    for app_client_pkg in ru.yandex.yandexnavi ru.yandex.yandexmaps com.yango.maps.android; do
        am force-stop "$app_client_pkg" >/dev/null 2>&1
    done
    rm -f /data/local/bin/fullscreen_client.js \
        /data/local/bin/fullscreen_client.js.voyahtune.new \
        /data/local/tmp/voyahtune_fullscreen_client.* \
        /data/local/tmp/voyahtune_app_client.* || exit 1
    [ -s /data/local/bin/app_client.js ] || exit 1
    [ ! -e /data/local/bin/fullscreen_client.js ] || exit 1
    [ ! -e /data/local/bin/fullscreen_client.js.voyahtune.new ] || exit 1
    ! ls /data/local/tmp/voyahtune_fullscreen_client.* >/dev/null 2>&1 || exit 1
    ! ls /data/local/tmp/voyahtune_app_client.* >/dev/null 2>&1 || exit 1
"###;
// Packaging/installer/light/install.sh:40
pub const STOP_LIGHT: &str = r###"
        setprop ctl.stop voyahtune_load 2>/dev/null || exit 1
        stop_wait=0
        while [ "$(getprop init.svc.voyahtune_load)" != "stopped" ]; do
            [ "$stop_wait" -lt 5 ] || exit 1
            sleep 1
            stop_wait=$((stop_wait + 1))
        done
    "###;
// Packaging/installer/light/install.sh:54
pub const LIGHT_TEARDOWN: &str = r###"
        ACTIVE_RC=/system/etc/init/voyahtune.load.rc
        DISABLED_RC=/system/etc/init/voyahtune.load.rc.voyahtune-light-disabled
        rm -f "$DISABLED_RC" || exit 1
        if [ -e "$ACTIVE_RC" ] || [ -L "$ACTIVE_RC" ]; then
            mv -f "$ACTIVE_RC" "$DISABLED_RC" || exit 1
        fi
        [ ! -e "$ACTIVE_RC" ] && [ ! -L "$ACTIVE_RC" ] || exit 1
        rm -f \
            /system/etc/init.voyahtune.load.sh \
            /system/etc/init/voyahtune.load.sh \
            /system/etc/init/voyahtune.setenforce.rc \
            /system/etc/.voyahtune.load.sh.new \
            /system/etc/.voyahtune.load.sh.previous \
            /system/etc/.voyahtune.load.sh.absent \
            /system/etc/.voyahtune.load.sh.rollback \
            /system/etc/.voyahtune.load.rc.new \
            /system/etc/.voyahtune.load.rc.previous \
            /system/etc/.voyahtune.load.rc.absent \
            /system/etc/.voyahtune.load.rc.rollback \
            /system/etc/.voyahtune.setenforce.rc.new \
            /system/etc/.voyahtune.setenforce.rc.previous \
            /system/etc/.voyahtune.setenforce.rc.absent \
            /system/etc/.voyahtune.setenforce.rc.rollback \
            "$DISABLED_RC" || exit 1

        # Eternalized app-client agents survive removal of their script file. Stop every configured
        # fullscreen host plus the three MapKit hosts before tearing down the full runtime.
        fullscreen_csv=$(settings get global voyahtune_fullscreen_apps 2>/dev/null)
        old_ifs=$IFS
        IFS=,
        for app_client_pkg in $fullscreen_csv; do
            IFS=$old_ifs
            case "$app_client_pkg" in
                ""|null|.*|*.|*..*|*[!A-Za-z0-9._]*) IFS=,; continue ;;
            esac
            am force-stop "$app_client_pkg" >/dev/null 2>&1
            IFS=,
        done
        IFS=$old_ifs
        for app_client_pkg in ru.yandex.yandexnavi ru.yandex.yandexmaps com.yango.maps.android; do
            am force-stop "$app_client_pkg" >/dev/null 2>&1
        done

        # load.bin/frida-inject могли существовать до VoyahTune, а их backup хранится в каталоге
        # исходного Full-релиза. Light не угадывает ownership generic binaries: project loader
        # удаляется только по двум ASCII marker, generic injector остаётся неактивным без boot path.
        if [ -f /data/local/bin/load.bin ] \
                && grep -qF LOG_TAG=vt_load_bin /data/local/bin/load.bin 2>/dev/null \
                && grep -qF LOAD_LOCK=/data/local/tmp/voyahtune_load.v2.lock \
                    /data/local/bin/load.bin 2>/dev/null; then
            rm -f /data/local/bin/load.bin || exit 1
        fi
        rm -f /data/local/bin/apollo_tech.js \
            /data/local/bin/apollo_tech.js.new \
            /data/local/bin/apollo_tech.js.voyahtune.new \
            /data/local/bin/load.bin.voyahtune.new \
            /data/local/bin/frida-inject.voyahtune.new \
            /data/local/bin/app_client.js \
            /data/local/bin/app_client.js.voyahtune.new \
            /data/local/bin/fullscreen_client.js \
            /data/local/bin/fullscreen_client.js.voyahtune.new \
            /data/local/bin/vd_bypass.js \
            /data/local/bin/vd_bypass.js.voyahtune.new \
            /data/local/bin/steeringwheelkeys.js \
            /data/local/bin/steeringwheelkeys.js.voyahtune.new \
            /data/local/bin/launcherdock.js \
            /data/local/bin/launcherdock.js.voyahtune.new \
            /data/local/bin/multidisplay.js \
            /data/local/bin/multidisplay.js.voyahtune.new \
            /data/local/bin/keymng2.js \
            /data/local/bin/keyboard_lock_en.js \
            /data/local/bin/keyboard_lock_en.js.voyahtune.new \
            /data/local/bin/keyboard_ru.js \
            /data/local/bin/keyboard_ru.js.voyahtune.new \
            /data/local/bin/voyahtune_keyboard_en_config.json \
            /data/local/bin/voyahtune_keyboard_en_config.json.voyahtune.new \
            /data/local/bin/voyahtune_keyboard_ru_config.json \
            /data/local/bin/voyahtune_keyboard_ru_config.json.voyahtune.new \
            /data/local/bin/voyahtune_skb_qwerty_ru.json \
            /data/local/bin/voyahtune_skb_qwerty_ru.json.voyahtune.new \
            /data/local/bin/voyahtune-hook-manifest.json \
            /data/local/bin/voyahtune-hook-manifest.json.voyahtune.new \
            /data/local/tmp/voyahtune_load.v2.lock \
            /data/local/tmp/voyah_load.v2.lock \
            /data/local/tmp/voyahtune_vd.pid \
            /data/local/tmp/voyahtune_vd.attempt \
            /data/local/tmp/voyahtune_vd_bypass.txt \
            /data/local/tmp/voyahtune_vd_bypass.txt.try \
            /data/local/tmp/voyahtune_swk_km.pid \
            /data/local/tmp/voyahtune_swk_km.busy \
            /data/local/tmp/voyahtune_swk_km.attempt \
            /data/local/tmp/voyahtune_swk.txt \
            /data/local/tmp/voyahtune_swk.try \
            /data/local/tmp/voyahtune_lnch.pid \
            /data/local/tmp/voyahtune_lnch.attempt \
            /data/local/tmp/voyahtune_lnch.txt \
            /data/local/tmp/voyahtune_lnch.txt.try \
            /data/local/tmp/voyahtune_md.pid \
            /data/local/tmp/voyahtune_md.attempt \
            /data/local/tmp/voyahtune_md.txt \
            /data/local/tmp/voyahtune_md.txt.try \
            /data/local/tmp/voyahtune_apollo.pid \
            /data/local/tmp/voyahtune_apollo.attempt \
            /data/local/tmp/voyahtune_apollo.txt \
            /data/local/tmp/voyahtune_apollo.txt.try \
            /data/local/tmp/voyahtune_keyboard.pid \
            /data/local/tmp/voyahtune_keyboard.attempt \
            /data/local/tmp/voyahtune_keyboard.txt \
            /data/local/tmp/voyahtune_keyboard.txt.try \
            /data/local/tmp/voyahtune_load.txt \
            /data/local/tmp/voyahtune-hook-status.v1 \
            /data/local/tmp/voyahtune-hook-status.v1.*.new \
            /data/local/tmp/voyah_vd.pid \
            /data/local/tmp/voyah_swk_ss.pid \
            /data/local/tmp/voyah_swk_km.pid \
            /data/local/tmp/voyah_swk_km.busy \
            /data/local/tmp/voyah_km.pid \
            /data/local/tmp/voyah_lnch.pid \
            /data/local/tmp/voyah_md.pid \
            /data/local/tmp/voyah_apollo.pid \
            /data/local/tmp/voyah_apollo.down \
            /data/local/tmp/voyah_apollo.disabled \
            /data/local/tmp/voyah_load.txt \
            /data/local/tmp/voyah_vd_bypass.txt \
            /data/local/tmp/voyah_vd_bypass.txt.try \
            /data/local/tmp/voyah_keymng.txt \
            /data/local/tmp/voyah_swk.txt \
            /data/local/tmp/voyah_swk.txt.try \
            /data/local/tmp/voyah_lnch.txt \
            /data/local/tmp/voyah_lnch.txt.try \
            /data/local/tmp/voyah_md.txt \
            /data/local/tmp/voyah_md.txt.try \
            /data/local/tmp/voyah_apollo.txt \
            /data/local/tmp/voyah_apollo.txt.1 \
            /data/local/tmp/voyah_apollo.txt.try || exit 1
        rm -f /data/local/tmp/voyahtune_app_client.* \
            /data/local/tmp/voyahtune_fullscreen_client.* || exit 1
        rm -rf /data/local/tmp/voyah_load.lock || exit 1
        for removed_path in \
                /system/etc/init/voyahtune.load.rc \
                /system/etc/init.voyahtune.load.sh \
                /system/etc/init/voyahtune.load.sh \
                /data/local/bin/vd_bypass.js \
                /data/local/bin/steeringwheelkeys.js \
                /data/local/bin/launcherdock.js \
                /data/local/bin/multidisplay.js \
                /data/local/bin/app_client.js \
                /data/local/bin/app_client.js.voyahtune.new \
                /data/local/bin/fullscreen_client.js \
                /data/local/bin/fullscreen_client.js.voyahtune.new \
                /data/local/bin/apollo_tech.js \
                /data/local/bin/keyboard_lock_en.js \
                /data/local/bin/keyboard_ru.js \
                /data/local/bin/voyahtune-hook-manifest.json \
                /data/local/tmp/voyahtune-hook-status.v1; do
            [ ! -e "$removed_path" ] && [ ! -L "$removed_path" ] || exit 1
        done
        ! ls /data/local/tmp/voyahtune_app_client.* >/dev/null 2>&1 || exit 1
        ! ls /data/local/tmp/voyahtune_fullscreen_client.* >/dev/null 2>&1 || exit 1
        sync
    "###;
// Packaging/installer/light/install.sh:406
pub const LIGHT_LEGACY_STATE: &str = r###"
    if [ ! -e /system/etc/init.logcat.sh ]; then
        echo CLEAN
    elif [ ! -f /system/etc/init.logcat.sh ]; then
        echo ERROR
    else
        grep -qF "# init.logcat.sh Open Voyah:" /system/etc/init.logcat.sh 2>/dev/null
        legacy_grep_status=$?
        if [ "$legacy_grep_status" -eq 0 ]; then
            echo LEGACY
        elif [ "$legacy_grep_status" -eq 1 ]; then
            echo CLEAN
        else
            echo ERROR
        fi
    fi
"###;
// Packaging/installer/full/remove.sh:196
pub const REMOVE_RW_TEST: &str = r###"touch /system/.ovw_remove_rwtest 2>/dev/null && rm -f /system/.ovw_remove_rwtest && echo RW || echo RO"###;
// Packaging/installer/full/remove.sh:245
pub const REMOVE_BOOT: &str = r###"rm -f /system/etc/init/voyahtune.load.rc /system/etc/init.voyahtune.load.sh /system/etc/init/voyahtune.load.sh /system/etc/init/voyahtune.setenforce.rc && test ! -e /system/etc/init/voyahtune.load.rc && test ! -e /system/etc/init.voyahtune.load.sh && test ! -e /system/etc/init/voyahtune.load.sh && test ! -e /system/etc/init/voyahtune.setenforce.rc"###;
// Packaging/installer/full/remove.sh:251
pub const REMOVE_TRANSACTIONS: &str = r###"rm -f /system/etc/.voyahtune.setenforce.rc.new /system/etc/.voyahtune.load.rc.new /system/etc/.voyahtune.load.sh.new /system/etc/.voyahtune.setenforce.rc.previous /system/etc/.voyahtune.setenforce.rc.absent /system/etc/.voyahtune.load.rc.previous /system/etc/.voyahtune.load.rc.absent /system/etc/.voyahtune.load.sh.previous /system/etc/.voyahtune.load.sh.absent /system/etc/.voyahtune.setenforce.rc.rollback /system/etc/.voyahtune.load.rc.rollback /system/etc/.voyahtune.load.sh.rollback /system/etc/init.logcat.sh.voyahtune.new /system/etc/init.logcat.sh.voyahtune.rollback"###;
// Packaging/installer/full/remove.sh:259
pub const REMOVE_PROCESSES: &str = r###"ps -ef | grep frida-inject | grep -E 'vd_bypass|steeringwheelkeys|launcherdock|multidisplay|apollo_tech|keyboard_lock_en|keyboard_ru|app_client|fullscreen_client' | grep -v grep | awk '{print $2}' | xargs kill -9"###;
// Packaging/installer/full/remove.sh:263
pub const STOP_FULLSCREEN: &str = r###"fullscreen_csv=$(settings get global voyahtune_fullscreen_apps 2>/dev/null); old_ifs=$IFS; IFS=,; for fullscreen_pkg in $fullscreen_csv; do IFS=$old_ifs; case "$fullscreen_pkg" in ""|*[!A-Za-z0-9._]*) IFS=,; continue;; esac; am force-stop "$fullscreen_pkg" >/dev/null 2>&1; IFS=,; done; IFS=$old_ifs"###;
// Packaging/installer/full/remove.sh:270
pub const REMOVE_EARLY_VD: &str = r###"rm -f /data/local/bin/vd_bypass.js"###;
// Packaging/installer/full/remove.sh:271
pub const REMOVE_EARLY_HOOKS: &str = r###"rm -f /data/local/bin/steeringwheelkeys.js /data/local/bin/launcherdock.js /data/local/bin/multidisplay.js /data/local/bin/keymng2.js"###;
// Packaging/installer/full/remove.sh:273
pub const REMOVE_EARLY_APOLLO: &str =
    r###"rm -f /data/local/bin/apollo_tech.js /data/local/bin/apollo_tech.js.new"###;
// Packaging/installer/full/remove.sh:274
pub const REMOVE_EARLY_KEYBOARD: &str = r###"rm -f /data/local/bin/keyboard_lock_en.js /data/local/bin/keyboard_ru.js /data/local/bin/voyahtune_keyboard_en_config.json /data/local/bin/voyahtune_keyboard_ru_config.json /data/local/bin/voyahtune_skb_qwerty_ru.json"###;
// Packaging/installer/full/remove.sh:275
pub const REMOVE_EARLY_FULLSCREEN: &str = r###"rm -f /data/local/bin/app_client.js /data/local/bin/app_client.js.voyahtune.new /data/local/bin/fullscreen_client.js /data/local/bin/fullscreen_client.js.voyahtune.new /data/local/tmp/voyahtune_app_client.* /data/local/tmp/voyahtune_fullscreen_client.*"###;
// Packaging/installer/full/remove.sh:276
pub const REMOVE_EARLY_MANIFEST: &str = r###"rm -f /data/local/bin/voyahtune-hook-manifest.json /data/local/tmp/voyahtune-hook-status.v1 /data/local/tmp/voyahtune-hook-status.v1.*.new"###;
// Packaging/installer/full/remove.sh:281
pub const REMOVE_FILES: &str = r###"
    rm -f \
        /data/local/bin/vd_bypass.js \
        /data/local/bin/steeringwheelkeys.js \
        /data/local/bin/launcherdock.js \
        /data/local/bin/multidisplay.js \
        /data/local/bin/keymng2.js \
        /data/local/bin/apollo_tech.js \
        /data/local/bin/apollo_tech.js.new \
        /data/local/bin/keyboard_lock_en.js \
        /data/local/bin/keyboard_ru.js \
        /data/local/bin/voyahtune_keyboard_en_config.json \
        /data/local/bin/voyahtune_keyboard_ru_config.json \
        /data/local/bin/voyahtune_skb_qwerty_ru.json \
        /data/local/tmp/voyahtune_keyboard.pid \
        /data/local/tmp/voyahtune_keyboard.attempt \
        /data/local/tmp/voyahtune_keyboard.txt \
        /data/local/tmp/voyahtune_keyboard.txt.try \
        /data/local/tmp/voyahtune_apollo.pid \
        /data/local/tmp/voyahtune_apollo.attempt \
        /data/local/tmp/voyahtune_apollo.txt \
        /data/local/tmp/voyahtune_apollo.txt.try \
        /data/local/tmp/voyahtune_load.v2.lock \
        /data/local/tmp/voyahtune_vd.pid \
        /data/local/tmp/voyahtune_vd.attempt \
        /data/local/tmp/voyahtune_swk_km.pid \
        /data/local/tmp/voyahtune_swk_km.busy \
        /data/local/tmp/voyahtune_swk_km.attempt \
        /data/local/tmp/voyahtune_lnch.pid \
        /data/local/tmp/voyahtune_lnch.attempt \
        /data/local/tmp/voyahtune_md.pid \
        /data/local/tmp/voyahtune_md.attempt \
        /data/local/tmp/voyahtune_load.txt \
        /data/local/tmp/voyahtune_vd_bypass.txt \
        /data/local/tmp/voyahtune_vd_bypass.txt.try \
        /data/local/tmp/voyahtune_swk.txt \
        /data/local/tmp/voyahtune_swk.try \
        /data/local/tmp/voyahtune_lnch.txt \
        /data/local/tmp/voyahtune_lnch.txt.try \
        /data/local/tmp/voyahtune_md.txt \
        /data/local/tmp/voyahtune_md.txt.try \
        /data/local/tmp/voyah_load.v2.lock \
        /data/local/tmp/voyah_vd.pid \
        /data/local/tmp/voyah_swk_ss.pid \
        /data/local/tmp/voyah_swk_km.pid \
        /data/local/tmp/voyah_swk_km.busy \
        /data/local/tmp/voyah_km.pid \
        /data/local/tmp/voyah_lnch.pid \
        /data/local/tmp/voyah_md.pid \
        /data/local/tmp/voyah_apollo.pid \
        /data/local/tmp/voyah_apollo.down \
        /data/local/tmp/voyah_apollo.disabled \
        /data/local/tmp/voyah_load.txt \
        /data/local/tmp/voyah_vd_bypass.txt \
        /data/local/tmp/voyah_vd_bypass.txt.try \
        /data/local/tmp/voyah_keymng.txt \
        /data/local/tmp/voyah_swk.txt \
        /data/local/tmp/voyah_swk.txt.try \
        /data/local/tmp/voyah_lnch.txt \
        /data/local/tmp/voyah_lnch.txt.try \
        /data/local/tmp/voyah_md.txt \
        /data/local/tmp/voyah_md.txt.try \
        /data/local/tmp/voyah_apollo.txt \
        /data/local/tmp/voyah_apollo.txt.1 \
        /data/local/tmp/voyah_apollo.txt.try \
        /data/local/tmp/open_voyah_dns_overlay.sh \
        /data/local/tmp/open_voyah_yandex_dns.apk \
        /sdcard/tmp/voyahtune_native_log.txt \
        /sdcard/tmp/voyah_native_log.txt && \
    rm -rf /data/local/tmp/voyah_load.lock /data/local/open_voyah && \
    for path in \
        /data/local/bin/vd_bypass.js \
        /data/local/bin/steeringwheelkeys.js \
        /data/local/bin/launcherdock.js \
        /data/local/bin/multidisplay.js \
        /data/local/bin/keymng2.js \
        /data/local/bin/apollo_tech.js \
        /data/local/bin/apollo_tech.js.new \
        /data/local/bin/keyboard_lock_en.js \
        /data/local/bin/keyboard_ru.js \
        /data/local/bin/voyahtune_keyboard_en_config.json \
        /data/local/bin/voyahtune_keyboard_ru_config.json \
        /data/local/bin/voyahtune_skb_qwerty_ru.json \
        /data/local/tmp/voyahtune_keyboard.pid \
        /data/local/tmp/voyahtune_keyboard.attempt \
        /data/local/tmp/voyahtune_keyboard.txt \
        /data/local/tmp/voyahtune_keyboard.txt.try \
        /data/local/tmp/voyahtune_apollo.pid \
        /data/local/tmp/voyahtune_apollo.attempt \
        /data/local/tmp/voyahtune_apollo.txt \
        /data/local/tmp/voyahtune_apollo.txt.try \
        /data/local/tmp/voyahtune_load.v2.lock \
        /data/local/tmp/voyahtune_vd.pid \
        /data/local/tmp/voyahtune_vd.attempt \
        /data/local/tmp/voyahtune_swk_km.pid \
        /data/local/tmp/voyahtune_swk_km.busy \
        /data/local/tmp/voyahtune_swk_km.attempt \
        /data/local/tmp/voyahtune_lnch.pid \
        /data/local/tmp/voyahtune_lnch.attempt \
        /data/local/tmp/voyahtune_md.pid \
        /data/local/tmp/voyahtune_md.attempt \
        /data/local/tmp/voyahtune_load.txt \
        /data/local/tmp/voyahtune_vd_bypass.txt \
        /data/local/tmp/voyahtune_vd_bypass.txt.try \
        /data/local/tmp/voyahtune_swk.txt \
        /data/local/tmp/voyahtune_swk.try \
        /data/local/tmp/voyahtune_lnch.txt \
        /data/local/tmp/voyahtune_lnch.txt.try \
        /data/local/tmp/voyahtune_md.txt \
        /data/local/tmp/voyahtune_md.txt.try \
        /data/local/tmp/voyah_load.v2.lock \
        /data/local/tmp/voyah_load.lock \
        /data/local/tmp/voyah_vd.pid \
        /data/local/tmp/voyah_swk_ss.pid \
        /data/local/tmp/voyah_swk_km.pid \
        /data/local/tmp/voyah_swk_km.busy \
        /data/local/tmp/voyah_km.pid \
        /data/local/tmp/voyah_lnch.pid \
        /data/local/tmp/voyah_md.pid \
        /data/local/tmp/voyah_apollo.pid \
        /data/local/tmp/voyah_apollo.down \
        /data/local/tmp/voyah_apollo.disabled \
        /data/local/tmp/voyah_load.txt \
        /data/local/tmp/voyah_vd_bypass.txt \
        /data/local/tmp/voyah_vd_bypass.txt.try \
        /data/local/tmp/voyah_keymng.txt \
        /data/local/tmp/voyah_swk.txt \
        /data/local/tmp/voyah_swk.txt.try \
        /data/local/tmp/voyah_lnch.txt \
        /data/local/tmp/voyah_lnch.txt.try \
        /data/local/tmp/voyah_md.txt \
        /data/local/tmp/voyah_md.txt.try \
        /data/local/tmp/voyah_apollo.txt \
        /data/local/tmp/voyah_apollo.txt.1 \
        /data/local/tmp/voyah_apollo.txt.try \
        /data/local/tmp/open_voyah_dns_overlay.sh \
        /data/local/tmp/open_voyah_yandex_dns.apk \
        /data/local/open_voyah \
        /sdcard/tmp/voyahtune_native_log.txt \
        /sdcard/tmp/voyah_native_log.txt; do
        if [ -e "$path" ] || [ -L "$path" ]; then exit 1; fi
    done
"###;
// Packaging/installer/full/remove.sh:438
pub const REMOVE_SETTINGS: &str = r###"
    for setting_name in \
        voyahtune_dock1 voyahtune_dock2 voyahtune_dock1Dpi voyahtune_dock2Dpi \
        voyahtune_dockPassenger1 voyahtune_dockPassenger2 \
        voyahtune_dockPassenger1Dpi voyahtune_dockPassenger2Dpi \
        voyahtune_screen_lift_type voyahtune_win_compact_bottom \
        voyahtune_fullscreen_apps \
        voyahtune_steerStarShort voyahtune_steerStarLong \
        voyahtune_steerDvrShort voyahtune_steerDvrLong \
        voyahtune_steerVoiceShort voyahtune_steerVoiceLong \
        voyahtune_steerPhoneShort voyahtune_steerPhoneLong \
        open_voyah_apollo_master open_voyah_apollo_legacy_hook_enabled \
        open_voyah_apollo_asc open_voyah_apollo_sdb \
        open_voyah_apollo_profile_supported open_voyah_apollo_profile_heartbeat \
        voyahtune_keyboard_mode \
        enable_freeform_support force_resizable_activities; do
        settings delete global "$setting_name" >/dev/null 2>&1 || exit 1
    done
"###;
// Packaging/installer/full/remove.sh:472
pub const REMOVE_PACKAGES: &str = r###"
    pm uninstall ru.big.town.anative >/dev/null 2>&1 || true
    pm uninstall --user 0 ru.big.town.anative >/dev/null 2>&1 || true
    pm uninstall ru.big.town.restoremode >/dev/null 2>&1 || true
    if pm path ru.big.town.anative 2>/dev/null | grep -q "^package:/data/app/"; then exit 1; fi
    if pm path ru.big.town.restoremode 2>/dev/null | grep -q "^package:"; then exit 1; fi
"###;
// Packaging/installer/full/remove.sh:483
pub const REMOVE_SYSTEM: &str = r###"rm -f /system/etc/permissions/privapp-permissions-ru.big.town.anative.xml /system/etc/.privapp-permissions-ru.big.town.anative.xml.voyahtune.new /system/priv-app/.Native.apk.voyahtune.new && rm -rf /system/priv-app/Native && test ! -e /system/etc/permissions/privapp-permissions-ru.big.town.anative.xml && test ! -e /system/etc/.privapp-permissions-ru.big.town.anative.xml.voyahtune.new && test ! -e /system/priv-app/.Native.apk.voyahtune.new && test ! -e /system/priv-app/Native"###;
// Packaging/installer/full/remove.sh:431
pub const REMOVE_CLIENT_CHECK: &str = r###"test ! -e /data/local/bin/app_client.js && test ! -e /data/local/bin/app_client.js.voyahtune.new && test ! -e /data/local/bin/fullscreen_client.js && test ! -e /data/local/bin/fullscreen_client.js.voyahtune.new && ! ls /data/local/tmp/voyahtune_app_client.* >/dev/null 2>&1 && ! ls /data/local/tmp/voyahtune_fullscreen_client.* >/dev/null 2>&1"###;
