package dev.dt2.qgyandexdns;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int config_ethernet_interfaces = 0x7f010000;
    }
}
