import pathlib
import re

VALUES = {
    "UNUSED": 0, "ANDROID_ORIENTATION": 1, "LAYOUT_CONSTRAINT_CIRCLE": 2,
    "LAYOUT_CONSTRAINT_CIRCLE_RADIUS": 3, "LAYOUT_CONSTRAINT_CIRCLE_ANGLE": 4,
    "LAYOUT_CONSTRAINT_GUIDE_BEGIN": 5, "LAYOUT_CONSTRAINT_GUIDE_END": 6,
    "LAYOUT_CONSTRAINT_GUIDE_PERCENT": 7, "LAYOUT_CONSTRAINT_LEFT_TO_LEFT_OF": 8,
    "LAYOUT_CONSTRAINT_LEFT_TO_RIGHT_OF": 9, "LAYOUT_CONSTRAINT_RIGHT_TO_LEFT_OF": 10,
    "LAYOUT_CONSTRAINT_RIGHT_TO_RIGHT_OF": 11, "LAYOUT_CONSTRAINT_TOP_TO_TOP_OF": 12,
    "LAYOUT_CONSTRAINT_TOP_TO_BOTTOM_OF": 13, "LAYOUT_CONSTRAINT_BOTTOM_TO_TOP_OF": 14,
    "LAYOUT_CONSTRAINT_BOTTOM_TO_BOTTOM_OF": 15, "LAYOUT_CONSTRAINT_BASELINE_TO_BASELINE_OF": 16,
    "LAYOUT_CONSTRAINT_START_TO_END_OF": 17, "LAYOUT_CONSTRAINT_START_TO_START_OF": 18,
    "LAYOUT_CONSTRAINT_END_TO_START_OF": 19, "LAYOUT_CONSTRAINT_END_TO_END_OF": 20,
    "LAYOUT_GONE_MARGIN_LEFT": 21, "LAYOUT_GONE_MARGIN_TOP": 22,
    "LAYOUT_GONE_MARGIN_RIGHT": 23, "LAYOUT_GONE_MARGIN_BOTTOM": 24,
    "LAYOUT_GONE_MARGIN_START": 25, "LAYOUT_GONE_MARGIN_END": 26,
    "LAYOUT_CONSTRAINED_WIDTH": 27, "LAYOUT_CONSTRAINED_HEIGHT": 28,
    "LAYOUT_CONSTRAINT_HORIZONTAL_BIAS": 29, "LAYOUT_CONSTRAINT_VERTICAL_BIAS": 30,
    "LAYOUT_CONSTRAINT_WIDTH_DEFAULT": 31, "LAYOUT_CONSTRAINT_HEIGHT_DEFAULT": 32,
    "LAYOUT_CONSTRAINT_WIDTH_MIN": 33, "LAYOUT_CONSTRAINT_WIDTH_MAX": 34,
    "LAYOUT_CONSTRAINT_WIDTH_PERCENT": 35, "LAYOUT_CONSTRAINT_HEIGHT_MIN": 36,
    "LAYOUT_CONSTRAINT_HEIGHT_MAX": 37, "LAYOUT_CONSTRAINT_HEIGHT_PERCENT": 38,
    "LAYOUT_CONSTRAINT_LEFT_CREATOR": 39, "LAYOUT_CONSTRAINT_TOP_CREATOR": 40,
    "LAYOUT_CONSTRAINT_RIGHT_CREATOR": 41, "LAYOUT_CONSTRAINT_BOTTOM_CREATOR": 42,
    "LAYOUT_CONSTRAINT_BASELINE_CREATOR": 43, "LAYOUT_CONSTRAINT_DIMENSION_RATIO": 44,
    "LAYOUT_CONSTRAINT_HORIZONTAL_WEIGHT": 45, "LAYOUT_CONSTRAINT_VERTICAL_WEIGHT": 46,
    "LAYOUT_CONSTRAINT_HORIZONTAL_CHAINSTYLE": 47, "LAYOUT_CONSTRAINT_VERTICAL_CHAINSTYLE": 48,
    "LAYOUT_EDITOR_ABSOLUTEX": 49, "LAYOUT_EDITOR_ABSOLUTEY": 50,
    "LAYOUT_CONSTRAINT_TAG": 51, "LAYOUT_CONSTRAINT_BASELINE_TO_TOP_OF": 52,
    "LAYOUT_CONSTRAINT_BASELINE_TO_BOTTOM_OF": 53, "LAYOUT_MARGIN_BASELINE": 54,
    "LAYOUT_GONE_MARGIN_BASELINE": 55, "LAYOUT_CONSTRAINT_WIDTH": 64,
    "LAYOUT_CONSTRAINT_HEIGHT": 65, "LAYOUT_WRAP_BEHAVIOR_IN_PARENT": 66,
    "GUIDELINE_USE_RTL": 67,
}

pat = re.compile(r"ConstraintLayout\.LayoutParams\.Table\.([A-Z_]+)")

root = pathlib.Path("RestoreMode/app/src/main/java")
total = 0
files = 0
for p in sorted(root.rglob("*.java")):
    t = p.read_text(encoding="utf-8", errors="replace")
    if "ConstraintLayout.LayoutParams.Table." not in t:
        continue

    def repl(m):
        name = m.group(1)
        if name not in VALUES:
            raise KeyError(f"unknown Table constant {name} in {p}")
        return str(VALUES[name])

    t2 = pat.sub(repl, t)
    if t2 != t:
        p.write_text(t2, encoding="utf-8")
        n = len(pat.findall(t))
        total += n
        files += 1

print(f"replaced {total} refs in {files} files")
