plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
    implementation 'org.yaml:snakeyaml:2.3'
    testImplementation 'junit:junit:4.13.2'
}

tasks.withType(Test).configureEach {
    useJUnit()
    testLogging {
        events 'failed'
        exceptionFormat 'full'
    }
}
