#!/usr/bin/env python3
"""Copy only device-side adb shell bodies into Rust constants. No host script is executed.
Run --check in tests; changes to classic scripts require reviewing the Rust control flow too.
"""
import argparse,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def commands(path):
 s=path.read_text();res={}
 for m in re.finditer(r'\badb shell\s+',s):
  i=m.end();start=i;quote=None;out=''
  while i<len(s):
   c=s[i]
   if quote is None and (c.isspace() or c in ';|)&<>'):break
   if c in "\"'" and quote is None:quote=c
   elif c==quote:quote=None
   elif c=='\\' and quote!="'" and i+1<len(s):
    n=s[i+1]
    if quote is None or n in '\\$`"\n':
     if n!='\n':out+=n
     i+=1
    else:out+=c
   else:out+=c
   i+=1
  if s[start:start+1] in "\"'":res[s.count('\n',0,m.start())+1]=out
 return res
SPECS={
 'full/install.sh':{'STOP_FULL':51,'NATIVE_READY':97,'NATIVE_BROADCAST':128,'MOUNT':184,'RW_TEST':185,'LEGACY_STATE':346,'LEGACY_ROLLBACK':391,'LEGACY_PUBLISH':450,'BOOT_CLEAN_STAGE':471,'BOOT_CLEAN_SNAPSHOT':475,'BOOT_STATE':479,'BOOT_SNAPSHOT':489,'BOOT_ROLLBACK':496,'BOOT_PREPARE':528,'BOOT_PUBLISH':541,'BOOT_READY':551,'BOOT_REMOVE_OLD':571,'APOLLO_FILES':616,'APP_CLIENT_MIGRATION':648},
 'light/install.sh':{'STOP_LIGHT':40,'LIGHT_TEARDOWN':54,'LIGHT_LEGACY_STATE':406},
 'full/remove.sh':{'REMOVE_RW_TEST':196,'REMOVE_BOOT':245,'REMOVE_TRANSACTIONS':251,'REMOVE_PROCESSES':259,'STOP_FULLSCREEN':263,'REMOVE_EARLY_VD':270,'REMOVE_EARLY_HOOKS':271,'REMOVE_EARLY_APOLLO':273,'REMOVE_EARLY_KEYBOARD':274,'REMOVE_EARLY_FULLSCREEN':275,'REMOVE_EARLY_MANIFEST':276,'REMOVE_FILES':281,'REMOVE_SETTINGS':438,'REMOVE_PACKAGES':472,'REMOVE_SYSTEM':483,'REMOVE_CLIENT_CHECK':431},
}
def render():
 out='// Device commands ported verbatim from Packaging/installer.\n// Generated by scripts/sync-classic-commands.py; control flow lives in engine.rs.\n'
 for source,items in SPECS.items():
  found=commands(ROOT/'Packaging/installer'/source)
  for name,line in items.items():
   out+=f'// Packaging/installer/{source}:{line}\npub const {name}: &str = r###"{found[line]}"###;\n'
 return out
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 target=ROOT/'Installer/crates/installer-core/src/classic_commands.rs';expected=render()
 if args.check:
  pattern=r'pub const (\w+): &str =\s*r###"(.*?)"###;'
  if dict(re.findall(pattern,target.read_text(),re.S))!=dict(re.findall(pattern,expected,re.S)):raise SystemExit('Classic ADB commands changed. Review the port and run sync-classic-commands.py.')
 else:target.write_text(expected)
