package com.k2fsa.sherpa.onnx;

import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.core.view.PointerIconCompat;
import kotlin.Metadata;
import kotlinx.coroutines.internal.LockFreeTaskQueueCore;

/* JADX INFO: compiled from: OfflineRecognizer.kt */
/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000\u000e\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\b\n\u0000\u001a\u0010\u0010\u0000\u001a\u0004\u0018\u00010\u00012\u0006\u0010\u0002\u001a\u00020\u0003¨\u0006\u0004"}, d2 = {"getOfflineModelConfig", "Lcom/k2fsa/sherpa/onnx/OfflineModelConfig;", "type", "", "sherpa_onnx_release"}, k = 2, mv = {1, 7, 1}, xi = 48)
public final class OfflineRecognizerKt {
    public static final OfflineModelConfig getOfflineModelConfig(int i) {
        switch (i) {
            case 0:
                return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-paraformer-zh-2023-09-14/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "paraformer", "sherpa-onnx-paraformer-zh-2023-09-14/tokens.txt", null, null, 27262973, null);
            case 1:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04/encoder-epoch-30-avg-4.int8.onnx", "icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04/decoder-epoch-30-avg-4.onnx", "icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04/joiner-epoch-30-avg-4.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04/tokens.txt", null, null, 27262974, null);
            case 2:
                return new OfflineModelConfig(null, null, new OfflineWhisperModelConfig("sherpa-onnx-whisper-tiny.en/tiny.en-encoder.int8.onnx", "sherpa-onnx-whisper-tiny.en/tiny.en-decoder.int8.onnx", null, null, 0, false, false, 124, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "whisper", "sherpa-onnx-whisper-tiny.en/tiny.en-tokens.txt", null, null, 27262971, null);
            case 3:
                return new OfflineModelConfig(null, null, new OfflineWhisperModelConfig("sherpa-onnx-whisper-base.en/base.en-encoder.int8.onnx", "sherpa-onnx-whisper-base.en/base.en-decoder.int8.onnx", null, null, 0, false, false, 124, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "whisper", "sherpa-onnx-whisper-base.en/base.en-tokens.txt", null, null, 27262971, null);
            case 4:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("icefall-asr-zipformer-wenetspeech-20230615/encoder-epoch-12-avg-4.int8.onnx", "icefall-asr-zipformer-wenetspeech-20230615/decoder-epoch-12-avg-4.onnx", "icefall-asr-zipformer-wenetspeech-20230615/joiner-epoch-12-avg-4.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "icefall-asr-zipformer-wenetspeech-20230615/tokens.txt", null, null, 27262974, null);
            case 5:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/encoder-epoch-20-avg-1.int8.onnx", "sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/decoder-epoch-20-avg-1.onnx", "sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/joiner-epoch-20-avg-1.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/tokens.txt", null, null, 27262974, null);
            case 6:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-ctc-en-citrinet-512/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-ctc-en-citrinet-512/tokens.txt", null, null, 29360095, null);
            case 7:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-fast-conformer-ctc-be-de-en-es-fr-hr-it-pl-ru-uk-20k/model.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-fast-conformer-ctc-be-de-en-es-fr-hr-it-pl-ru-uk-20k/tokens.txt", null, null, 29360095, null);
            case 8:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-fast-conformer-ctc-en-24500/model.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-fast-conformer-ctc-en-24500/tokens.txt", null, null, 29360095, null);
            case 9:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-fast-conformer-ctc-en-de-es-fr-14288/model.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-fast-conformer-ctc-en-de-es-fr-14288/tokens.txt", null, null, 29360095, null);
            case 10:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-fast-conformer-ctc-es-1424/model.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-fast-conformer-ctc-es-1424/tokens.txt", null, null, 29360095, null);
            case 11:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "sherpa-onnx-telespeech-ctc-int8-zh-2024-06-04/model.int8.onnx", 0, false, null, "telespeech_ctc", "sherpa-onnx-telespeech-ctc-int8-zh-2024-06-04/tokens.txt", null, null, 27131903, null);
            case 12:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-thai-2024-06-20/encoder-epoch-12-avg-5.int8.onnx", "sherpa-onnx-zipformer-thai-2024-06-20/decoder-epoch-12-avg-5.onnx", "sherpa-onnx-zipformer-thai-2024-06-20/joiner-epoch-12-avg-5.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-thai-2024-06-20/tokens.txt", null, null, 27262974, null);
            case 13:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-korean-2024-06-24/encoder-epoch-99-avg-1.int8.onnx", "sherpa-onnx-zipformer-korean-2024-06-24/decoder-epoch-99-avg-1.onnx", "sherpa-onnx-zipformer-korean-2024-06-24/joiner-epoch-99-avg-1.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-korean-2024-06-24/tokens.txt", null, null, 27262974, null);
            case 14:
                return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-paraformer-zh-small-2024-03-09/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "paraformer", "sherpa-onnx-paraformer-zh-small-2024-03-09/tokens.txt", null, null, 27262973, null);
            case 15:
                return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17/model.int8.onnx", null, false, null, 14, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17/tokens.txt", null, null, 29360063, null);
            case 16:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01/encoder-epoch-99-avg-1.int8.onnx", "sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01/decoder-epoch-99-avg-1.onnx", "sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01/joiner-epoch-99-avg-1.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01/tokens.txt", null, null, 27262974, null);
            case 17:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-ru-2024-09-18/encoder.int8.onnx", "sherpa-onnx-zipformer-ru-2024-09-18/decoder.onnx", "sherpa-onnx-zipformer-ru-2024-09-18/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-ru-2024-09-18/tokens.txt", null, null, 27262974, null);
            case 18:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-small-zipformer-ru-2024-09-18/encoder.int8.onnx", "sherpa-onnx-small-zipformer-ru-2024-09-18/decoder.onnx", "sherpa-onnx-small-zipformer-ru-2024-09-18/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-small-zipformer-ru-2024-09-18/tokens.txt", null, null, 27262974, null);
            case 19:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-ctc-giga-am-russian-2024-10-24/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-ctc-giga-am-russian-2024-10-24/tokens.txt", null, null, 29360095, null);
            case 20:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/encoder.int8.onnx", "sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/decoder.onnx", "sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/joiner.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/tokens.txt", null, null, 27262974, null);
            case 21:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig("sherpa-onnx-moonshine-tiny-en-int8/preprocess.onnx", "sherpa-onnx-moonshine-tiny-en-int8/encode.int8.onnx", "sherpa-onnx-moonshine-tiny-en-int8/uncached_decode.int8.onnx", "sherpa-onnx-moonshine-tiny-en-int8/cached_decode.int8.onnx", null, 16, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-tiny-en-int8/tokens.txt", null, null, 29360111, null);
            case 22:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig("sherpa-onnx-moonshine-base-en-int8/preprocess.onnx", "sherpa-onnx-moonshine-base-en-int8/encode.int8.onnx", "sherpa-onnx-moonshine-base-en-int8/uncached_decode.int8.onnx", "sherpa-onnx-moonshine-base-en-int8/cached_decode.int8.onnx", null, 16, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-en-int8/tokens.txt", null, null, 29360111, null);
            case 23:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-zh-en-2023-11-22/encoder-epoch-34-avg-19.int8.onnx", "sherpa-onnx-zipformer-zh-en-2023-11-22/decoder-epoch-34-avg-19.onnx", "sherpa-onnx-zipformer-zh-en-2023-11-22/joiner-epoch-34-avg-19.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-zh-en-2023-11-22/tokens.txt", null, null, 27262974, null);
            case 24:
                return new OfflineModelConfig(null, null, null, new OfflineFireRedAsrModelConfig("sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/encoder.int8.onnx", "sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/decoder.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/tokens.txt", null, null, 29360119, null);
            case 25:
                return new OfflineModelConfig(null, null, null, null, null, null, null, new OfflineDolphinModelConfig("sherpa-onnx-dolphin-base-ctc-multi-lang-int8-2025-04-02/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-dolphin-base-ctc-multi-lang-int8-2025-04-02/tokens.txt", null, null, 29359999, null);
            case 26:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-vi-int8-2025-04-20/encoder-epoch-12-avg-8.int8.onnx", "sherpa-onnx-zipformer-vi-int8-2025-04-20/decoder-epoch-12-avg-8.onnx", "sherpa-onnx-zipformer-vi-int8-2025-04-20/joiner-epoch-12-avg-8.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-vi-int8-2025-04-20/tokens.txt", null, null, 27262974, null);
            case 27:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-ctc-giga-am-v2-russian-2025-04-19/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-ctc-giga-am-v2-russian-2025-04-19/tokens.txt", null, null, 29360095, null);
            case 28:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/encoder.int8.onnx", "sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/decoder.onnx", "sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/joiner.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19/tokens.txt", null, null, 27262974, null);
            case 29 /* 29 */:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-ru-int8-2025-04-20/encoder.int8.onnx", "sherpa-onnx-zipformer-ru-int8-2025-04-20/decoder.onnx", "sherpa-onnx-zipformer-ru-int8-2025-04-20/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-ru-int8-2025-04-20/tokens.txt", null, null, 27262974, null);
            case 30:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/encoder.int8.onnx", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/decoder.int8.onnx", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/tokens.txt", null, null, 27262974, null);
            case 31 /* 31 */:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-zipformer-ctc-zh-int8-2025-07-03/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-zipformer-ctc-zh-int8-2025-07-03/tokens.txt", null, null, 29359871, null);
            case 32:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, new OfflineCanaryModelConfig("sherpa-onnx-nemo-canary-180m-flash-en-es-de-fr-int8/encoder.int8.onnx", "sherpa-onnx-nemo-canary-180m-flash-en-es-de-fr-int8/decoder.int8.onnx", "en", "en", true), null, null, 0, false, null, null, "sherpa-onnx-nemo-canary-180m-flash-en-es-de-fr-int8/tokens.txt", null, null, 29327359, null);
            case 33:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-parakeet_tdt_ctc_110m-en-36000-int8/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-parakeet_tdt_ctc_110m-en-36000-int8/tokens.txt", null, null, 29360095, null);
            case 34:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-parakeet-tdt_ctc-0.6b-ja-35000-int8/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-parakeet-tdt_ctc-0.6b-ja-35000-int8/tokens.txt", null, null, 29360095, null);
            case 35:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8/encoder.int8.onnx", "sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8/decoder.int8.onnx", "sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8/tokens.txt", null, null, 27262974, null);
            case 36:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-stt_pt_fastconformer_hybrid_large_pc-int8/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-stt_pt_fastconformer_hybrid_large_pc-int8/tokens.txt", null, null, 29360095, null);
            case 37:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8/encoder.int8.onnx", "sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8/decoder.int8.onnx", "sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8/tokens.txt", null, null, 27262974, null);
            case 38:
                return new OfflineModelConfig(null, null, null, null, null, new OfflineNemoEncDecCtcModelConfig("sherpa-onnx-nemo-stt_de_fastconformer_hybrid_large_pc-int8/model.int8.onnx"), null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-nemo-stt_de_fastconformer_hybrid_large_pc-int8/tokens.txt", null, null, 29360095, null);
            case 39:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-zipformer-ctc-small-zh-int8-2025-07-16/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-zipformer-ctc-small-zh-int8-2025-07-16/tokens.txt", null, null, 29359871, null);
            case 40:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/encoder.int8.onnx", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/decoder.int8.onnx", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/tokens.txt", null, null, 27262974, null);
            case 41:
                return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09/model.int8.onnx", null, false, null, 14, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09/tokens.txt", null, null, 29360063, null);
            case 42:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, new OfflineWenetCtcModelConfig("sherpa-onnx-wenetspeech-yue-u2pp-conformer-ctc-zh-en-cantonese-int8-2025-09-10/model.int8.onnx"), null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-wenetspeech-yue-u2pp-conformer-ctc-zh-en-cantonese-int8-2025-09-10/tokens.txt", null, null, 29359615, null);
            case 43:
                return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-paraformer-zh-int8-2025-10-07/model.int8.onnx", null, 2, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "paraformer", "sherpa-onnx-paraformer-zh-int8-2025-10-07/tokens.txt", null, null, 27262973, null);
            case 44:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, new OfflineOmnilingualAsrCtcModelConfig("sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-int8-2025-11-12/model.int8.onnx"), null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-int8-2025-11-12/tokens.txt", null, null, 29359103, null);
            case 45:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, new OfflineMedAsrCtcModelConfig("sherpa-onnx-medasr-ctc-en-int8-2025-12-25/model.int8.onnx"), null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-medasr-ctc-en-int8-2025-12-25/tokens.txt", null, null, 29358079, null);
            case 46:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, new OfflineFunAsrNanoModelConfig("sherpa-onnx-funasr-nano-int8-2025-12-30/encoder_adaptor.int8.onnx", "sherpa-onnx-funasr-nano-int8-2025-12-30/llm.int8.onnx", "sherpa-onnx-funasr-nano-int8-2025-12-30/embedding.int8.onnx", "sherpa-onnx-funasr-nano-int8-2025-12-30/Qwen3-0.6B", null, null, 0, 0.0f, 0.0f, 0, null, false, null, 8176, null), null, null, null, null, null, 3, false, null, null, "", null, null, 29093887, null);
            case 47:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, new OfflineWenetCtcModelConfig("sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-int8-2026-02-03/model.int8.onnx"), null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-int8-2026-02-03/tokens.txt", null, null, 29359615, null);
            case 48 /* 48 */:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, new OfflineWenetCtcModelConfig("sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-2026-02-03/model.onnx"), null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-2026-02-03/tokens.txt", null, null, 29359615, null);
            case 49 /* 49 */:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-zipformer-vi-30M-int8-2026-02-09/encoder.int8.onnx", "sherpa-onnx-zipformer-vi-30M-int8-2026-02-09/decoder.onnx", "sherpa-onnx-zipformer-vi-30M-int8-2026-02-09/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "transducer", "sherpa-onnx-zipformer-vi-30M-int8-2026-02-09/tokens.txt", null, null, 27262974, null);
            case 50:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, null, null, new OfflineFireRedAsrCtcModelConfig("sherpa-onnx-fire-red-asr2-ctc-zh_en-int8-2026-02-25/model.int8.onnx"), null, null, null, 0, false, null, null, "sherpa-onnx-fire-red-asr2-ctc-zh_en-int8-2026-02-25/tokens.txt", null, null, 29343743, null);
            case 51 /* 51 */:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-tiny-ko-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-tiny-ko-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-tiny-ko-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case 52 /* 52 */:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-tiny-ja-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-tiny-ja-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-tiny-ja-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case 53 /* 53 */:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-tiny-en-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-tiny-en-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-tiny-en-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case 54 /* 54 */:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-zh-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-zh-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-zh-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case 55 /* 55 */:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-vi-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-vi-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-vi-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case 56:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-uk-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-uk-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-uk-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case 57:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-ja-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-ja-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-ja-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case 58:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-es-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-es-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-es-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case 59:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-en-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-en-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-en-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case LockFreeTaskQueueCore.FROZEN_SHIFT /* 60 */:
                return new OfflineModelConfig(null, null, null, null, new OfflineMoonshineModelConfig(null, "sherpa-onnx-moonshine-base-ar-quantized-2026-02-27/encoder_model.ort", null, null, "sherpa-onnx-moonshine-base-ar-quantized-2026-02-27/decoder_model_merged.ort", 13, null), null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, null, "sherpa-onnx-moonshine-base-ar-quantized-2026-02-27/tokens.txt", null, null, 29360111, null);
            case LockFreeTaskQueueCore.CLOSED_SHIFT /* 61 */:
                return new OfflineModelConfig(null, null, null, null, null, null, null, null, null, null, null, null, null, new OfflineQwen3AsrModelConfig("sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25/conv_frontend.onnx", "sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25/encoder.int8.onnx", "sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25/decoder.int8.onnx", "sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25/tokenizer", 0, 0, 0.0f, 0.0f, 0, null, PointerIconCompat.TYPE_TEXT, null), null, null, null, null, 3, false, null, null, "", null, null, 29089791, null);
            case 62:
                return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming/encoder.int8.onnx", "sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming/decoder.int8.onnx", "sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming/joiner.int8.onnx", null, 8, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, false, null, "nemo_transducer", "sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming/tokens.txt", null, null, 27262974, null);
            default:
                switch (i) {
                    case 9000:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-5-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-5-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-5-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 27787199, null);
                    case 9001:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-8-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-8-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-8-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 27787199, null);
                    case 9002:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 27787199, null);
                    case 9003:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-13-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-13-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-13-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                    case 9004:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-15-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-15-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-15-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                    case 9005:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-18-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-18-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-18-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                    case 9006:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-20-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-20-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-20-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                    case 9007:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-23-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-23-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-23-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                    case 9008:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-25-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-25-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-25-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                    case 9009:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-28-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-28-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-28-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                    case 9010:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig("sherpa-onnx-qnn-30-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/libmodel.so", null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-30-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/model.bin", "libQnnSystem.so"), 6, null), null, null, null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-30-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8-android-aarch64/tokens.txt", null, null, 28311487, null);
                    case 9011:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-5-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-5-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-5-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 27787007, null);
                    case 9012:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-8-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-8-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-8-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 27787007, null);
                    case 9013:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-10-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-10-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-10-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 27787007, null);
                    case 9014:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-13-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-13-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-13-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                    case 9015:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-15-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-15-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-15-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                    case 9016:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-18-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-18-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-18-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                    case 9017:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-20-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-20-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-20-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                    case 9018:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-23-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-23-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-23-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                    case 9019:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-25-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-25-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-25-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                    case 9020:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-28-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-28-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-28-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                    case 9021:
                        return new OfflineModelConfig(null, null, null, null, null, null, null, null, new OfflineZipformerCtcModelConfig("sherpa-onnx-qnn-30-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/libmodel.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-30-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/model.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, 0, false, "qnn", null, "sherpa-onnx-qnn-30-seconds-zipformer-ctc-zh-2025-07-03-int8-android-aarch64/tokens.txt", null, null, 28311295, null);
                    case 9022:
                        return new OfflineModelConfig(null, null, null, null, null, null, new OfflineSenseVoiceModelConfig(null, null, false, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-SM8850-binary-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8/model.bin", "libQnnSystem.so"), 7, null), null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-SM8850-binary-10-seconds-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8/tokens.txt", null, null, 27787199, null);
                    case 9023:
                        return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/libencoder.so,sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/libpredictor.so,sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/libdecoder.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/encoder.bin,sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/predictor.bin,sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/decoder.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-5-seconds-paraformer-zh-2023-03-28-int8-android-aarch64/tokens.txt", null, null, 27787261, null);
                    case 9024:
                        return new OfflineModelConfig(null, new OfflineParaformerModelConfig("sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/libencoder.so,sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/libpredictor.so,sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/libdecoder.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/encoder.bin,sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/predictor.bin,sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/decoder.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-5-seconds-paraformer-zh-2025-10-07-int8-android-aarch64/tokens.txt", null, null, 27787261, null);
                    case 9025:
                        return new OfflineModelConfig(null, new OfflineParaformerModelConfig(null, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-SM8850-binary-5-seconds-paraformer-zh-2023-03-28-int8/encoder.bin,sherpa-onnx-qnn-SM8850-binary-5-seconds-paraformer-zh-2023-03-28-int8/predictor.bin,sherpa-onnx-qnn-SM8850-binary-5-seconds-paraformer-zh-2023-03-28-int8/decoder.bin", "libQnnSystem.so"), 1, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", null, "sherpa-onnx-qnn-SM8850-binary-5-seconds-paraformer-zh-2023-03-28-int8/tokens.txt", null, null, 27787261, null);
                    case 9026:
                        return new OfflineModelConfig(new OfflineTransducerModelConfig("sherpa-onnx-qnn-reazonspeech-zipformer-transducer-ja-5s-2024-08-01-android-aarch64/libencoder.so", "sherpa-onnx-qnn-reazonspeech-zipformer-transducer-ja-5s-2024-08-01-android-aarch64/libdecoder.so", "sherpa-onnx-qnn-reazonspeech-zipformer-transducer-ja-5s-2024-08-01-android-aarch64/libjoiner.so", new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-reazonspeech-zipformer-transducer-ja-5s-2024-08-01-android-aarch64/encoder.bin,sherpa-onnx-qnn-reazonspeech-zipformer-transducer-ja-5s-2024-08-01-android-aarch64/decoder.bin,sherpa-onnx-qnn-reazonspeech-zipformer-transducer-ja-5s-2024-08-01-android-aarch64/joiner.bin", "libQnnSystem.so")), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", "transducer", "sherpa-onnx-qnn-reazonspeech-zipformer-transducer-ja-5s-2024-08-01-android-aarch64/tokens.txt", null, null, 25690110, null);
                    case 9027:
                        return new OfflineModelConfig(new OfflineTransducerModelConfig(null, null, null, new QnnConfig("libQnnHtp.so", "sherpa-onnx-qnn-SM8850-binary-reazonspeech-zipformer-transducer-ja-5s-2024-08-01/encoder.bin,sherpa-onnx-qnn-SM8850-binary-reazonspeech-zipformer-transducer-ja-5s-2024-08-01/decoder.bin,sherpa-onnx-qnn-SM8850-binary-reazonspeech-zipformer-transducer-ja-5s-2024-08-01/joiner.bin", "libQnnSystem.so"), 7, null), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, true, "qnn", "transducer", "sherpa-onnx-qnn-SM8850-binary-reazonspeech-zipformer-transducer-ja-5s-2024-08-01/tokens.txt", null, null, 25690110, null);
                    default:
                        return null;
                }
        }
    }
}
